GOBIN := $(shell go env GOPATH)/bin
export PATH := $(PATH):$(GOBIN)

.PHONY: tools generate tidy build run docker-up docker-down migrate-up migrate-down test \
        k8s-secret k8s-images k8s-apply k8s-restart k8s-deploy k8s-status k8s-logs k8s-nuke \
        engine-image engine-restart engine-deploy ledger-image ledger-restart ledger-deploy \
        auth-image auth-restart auth-deploy shell-image shell-restart shell-deploy \
        admin-image admin-restart admin-deploy \
        gateway-image gateway-restart gateway-deploy \
        image-service-image image-miniapp-image coffee-service-image coffee-miniapp-image \
        image-deploy coffee-deploy examples-deploy

# --- Kubernetes demo deploy -------------------------------------------------
# The cluster runs on a remote node reachable over SSH. Images are built there
# (docker) and imported into containerd's k8s.io namespace, mirroring the other
# services on that node. kubectl runs locally against the same cluster.
SSH_HOST     ?= genMachine
REMOTE_DIR   ?= ~/sc-build
K8S_NS       ?= serviceconstructor
K8S_DIR      := deploy/k8s
# Repo root (parent of engine/ and ledger/) — engine's Dockerfile build context.
REPO_ROOT    := $(abspath ..)

# Generate the real, gitignored Secret with fresh random credentials.
k8s-secret:
	@umask 077; { \
	  echo '# REAL secret — gitignored. Generated by "make k8s-secret".'; \
	  echo '# Template: deploy/k8s/10-secret.example.yaml'; \
	  echo 'apiVersion: v1'; \
	  echo 'kind: Secret'; \
	  echo 'metadata:'; \
	  echo '  name: serviceconstructor-secrets'; \
	  echo '  namespace: $(K8S_NS)'; \
	  echo 'type: Opaque'; \
	  echo 'stringData:'; \
	  echo "  POSTGRES_PASSWORD: \"$$(openssl rand -hex 16)\""; \
	  echo "  AUTH_JWT_SECRET: \"$$(openssl rand -hex 32)\""; \
	} > $(K8S_DIR)/10-secret.yaml
	@echo "wrote $(K8S_DIR)/10-secret.yaml (gitignored)"

# Build+import every service image (delegates to per-service targets).
k8s-images: ledger-image engine-image auth-image gateway-image shell-image admin-image \
            image-service-image image-miniapp-image coffee-service-image coffee-miniapp-image

# --- Per-service build + rollout (faster when you touched only one service) --
# engine: build context is the repo root (needs the sibling ledger module for
# the `replace` directive), so we sync both and build from REMOTE_DIR.
engine-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' \
	  $(REPO_ROOT)/engine $(REPO_ROOT)/ledger $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f engine/Dockerfile -t serviceconstructor-engine:latest . && \
	  sudo docker save serviceconstructor-engine:latest | sudo ctr -n k8s.io images import -'

engine-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/engine
	kubectl -n $(K8S_NS) rollout status  deploy/engine --timeout=120s

engine-deploy: engine-image engine-restart

# ledger: self-contained module, build context is ledger/ itself.
ledger-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' \
	  $(REPO_ROOT)/ledger $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f ledger/Dockerfile -t serviceconstructor-ledger:latest ledger/ && \
	  sudo docker save serviceconstructor-ledger:latest | sudo ctr -n k8s.io images import -'

ledger-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/ledger
	kubectl -n $(K8S_NS) rollout status  deploy/ledger --timeout=120s

ledger-deploy: ledger-image ledger-restart

# auth: build context is the repo root (needs the sibling ledger module for the
# `replace` directive), same as engine.
auth-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' \
	  $(REPO_ROOT)/auth $(REPO_ROOT)/ledger $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f auth/Dockerfile -t serviceconstructor-auth:latest . && \
	  sudo docker save serviceconstructor-auth:latest | sudo ctr -n k8s.io images import -'

auth-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/auth
	kubectl -n $(K8S_NS) rollout status  deploy/auth --timeout=120s

auth-deploy: auth-image auth-restart

# wallet-shell: node build, self-contained context in wallet-shell/.
shell-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude '*.tsbuildinfo' \
	  $(REPO_ROOT)/wallet-shell $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f wallet-shell/Dockerfile -t serviceconstructor-shell:latest wallet-shell/ && \
	  sudo docker save serviceconstructor-shell:latest | sudo ctr -n k8s.io images import -'

shell-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/wallet-shell
	kubectl -n $(K8S_NS) rollout status  deploy/wallet-shell --timeout=120s

shell-deploy: shell-image shell-restart

# admin-ui: static SPA + nginx proxy, self-contained context in admin-ui/.
admin-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude '*.tsbuildinfo' \
	  $(REPO_ROOT)/admin-ui $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f admin-ui/Dockerfile -t serviceconstructor-admin:latest admin-ui/ && \
	  sudo docker save serviceconstructor-admin:latest | sudo ctr -n k8s.io images import -'

admin-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/admin-ui
	kubectl -n $(K8S_NS) rollout status  deploy/admin-ui --timeout=120s

admin-deploy: admin-image admin-restart

# gateway: self-contained Go module (own proto copies).
gateway-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'bin' \
	  $(REPO_ROOT)/gateway $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f gateway/Dockerfile -t serviceconstructor-gateway:latest gateway/ && \
	  sudo docker save serviceconstructor-gateway:latest | sudo ctr -n k8s.io images import -'

gateway-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/gateway
	kubectl -n $(K8S_NS) rollout status  deploy/gateway --timeout=120s

gateway-deploy: gateway-image gateway-restart

# --- Example services + mini-apps (image, coffee) --------------------------
# EXAMPLES_ROOT is the parent dir holding example-* projects (same as REPO_ROOT).
image-service-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude 'keys' \
	  $(REPO_ROOT)/example-image-service $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f example-image-service/Dockerfile -t serviceconstructor-image-service:latest example-image-service/ && \
	  sudo docker save serviceconstructor-image-service:latest | sudo ctr -n k8s.io images import -'

image-miniapp-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude '*.tsbuildinfo' \
	  $(REPO_ROOT)/example-image-miniapp $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f example-image-miniapp/Dockerfile -t serviceconstructor-image-miniapp:latest example-image-miniapp/ && \
	  sudo docker save serviceconstructor-image-miniapp:latest | sudo ctr -n k8s.io images import -'

coffee-service-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'keys' \
	  $(REPO_ROOT)/example-coffee-service $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f example-coffee-service/Dockerfile -t serviceconstructor-coffee-service:latest example-coffee-service/ && \
	  sudo docker save serviceconstructor-coffee-service:latest | sudo ctr -n k8s.io images import -'

coffee-miniapp-image:
	rsync -az --delete --exclude '.git' --exclude 'node_modules' --exclude 'dist' --exclude '*.tsbuildinfo' \
	  $(REPO_ROOT)/example-coffee-miniapp $(SSH_HOST):$(REMOTE_DIR)/
	ssh $(SSH_HOST) 'cd $(REMOTE_DIR) && \
	  DOCKER_BUILDKIT=0 sudo -E docker build -f example-coffee-miniapp/Dockerfile -t serviceconstructor-coffee-miniapp:latest example-coffee-miniapp/ && \
	  sudo docker save serviceconstructor-coffee-miniapp:latest | sudo ctr -n k8s.io images import -'

image-deploy: image-service-image image-miniapp-image
	kubectl apply -f $(K8S_DIR)/80-image.yaml
	kubectl -n $(K8S_NS) rollout restart deploy/image-service deploy/image-miniapp
	kubectl -n $(K8S_NS) rollout status  deploy/image-service --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/image-miniapp --timeout=120s

coffee-deploy: coffee-service-image coffee-miniapp-image
	kubectl apply -f $(K8S_DIR)/85-coffee.yaml
	kubectl -n $(K8S_NS) rollout restart deploy/coffee-service deploy/coffee-miniapp
	kubectl -n $(K8S_NS) rollout status  deploy/coffee-service --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/coffee-miniapp --timeout=120s

examples-deploy: image-deploy coffee-deploy

# Apply all manifests (namespace, secret, postgres, ledger, auth, engine, ingress, shell, admin, examples).
k8s-apply:
	kubectl apply -f $(K8S_DIR)/00-namespace.yaml
	kubectl apply -f $(K8S_DIR)/10-secret.yaml
	kubectl apply -f $(K8S_DIR)/20-postgres.yaml
	kubectl apply -f $(K8S_DIR)/30-ledger.yaml
	kubectl apply -f $(K8S_DIR)/35-auth.yaml
	kubectl apply -f $(K8S_DIR)/05-gateway.yaml
	kubectl apply -f $(K8S_DIR)/40-engine.yaml
	kubectl apply -f $(K8S_DIR)/50-ingress.yaml
	kubectl apply -f $(K8S_DIR)/60-wallet-shell.yaml
	kubectl apply -f $(K8S_DIR)/70-admin-ui.yaml
	kubectl apply -f $(K8S_DIR)/80-image.yaml
	kubectl apply -f $(K8S_DIR)/85-coffee.yaml

# Roll all app pods to pick up freshly imported :latest images.
k8s-restart:
	kubectl -n $(K8S_NS) rollout restart deploy/ledger deploy/auth deploy/engine deploy/wallet-shell deploy/admin-ui
	kubectl -n $(K8S_NS) rollout status  deploy/ledger       --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/auth         --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/engine       --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/wallet-shell --timeout=120s
	kubectl -n $(K8S_NS) rollout status  deploy/admin-ui     --timeout=120s

# Full redeploy: rebuild images, apply manifests, restart app pods.
k8s-deploy: k8s-images k8s-apply k8s-restart

k8s-status:
	kubectl -n $(K8S_NS) get pods,svc,ingress,certificate

k8s-logs:
	kubectl -n $(K8S_NS) logs -l app=engine --tail=50 -f

# DESTRUCTIVE: delete the whole namespace and the Postgres PV (wipes demo data).
# Prompts for confirmation; set CONFIRM=yes to skip (e.g. in scripts).
k8s-nuke:
	@if [ "$(CONFIRM)" != "yes" ]; then \
	  printf 'This DELETES namespace "%s", its PV, and wipes Postgres data on %s.\nType "yes" to continue: ' '$(K8S_NS)' '$(SSH_HOST)'; \
	  read ans; [ "$$ans" = "yes" ] || { echo "aborted."; exit 1; }; \
	fi
	kubectl delete namespace $(K8S_NS) --ignore-not-found
	kubectl delete pv serviceconstructor-pgdata --ignore-not-found
	ssh $(SSH_HOST) 'sudo rm -rf /data/serviceconstructor/pgdata'
# ---------------------------------------------------------------------------


# Install codegen plugins pinned alongside the module.
tools:
	go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
	go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest

# Generate Go stubs, gRPC server and HTTP gateway from proto.
generate:
	buf generate --path proto/serviceconstructor

tidy:
	go mod tidy

build:
	go build -o bin/server ./cmd/server

run:
	go run ./cmd/server

docker-up:
	docker compose -f deploy/docker-compose.yml up -d

docker-down:
	docker compose -f deploy/docker-compose.yml down

test:
	go test ./...
